spring:
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  #documents: classpath:swagger/markdown/**
# springdoc-openapi项目配置
springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '1-基础调试及配置'
      paths-to-match: '/api/face/basics/**'
      packages-to-scan: com.shuishu.face.openvisual.server.controller
    - group: '2-人脸服务使用'
      paths-to-match: '/api/face/server/**,/api/face/data/**'
      packages-to-scan: com.shuishu.face.openvisual.server.controller


